### PR TITLE
logo given by Shreyan

### PR DESCRIPTION
**Pull request by Shreyan-12345**
## JWOC Project 📝

Thanks for your participation in this project for JWOC. 
The contribution will help you get a nice understanding of Android Development. 

Stay determined, stay motivated and Happy Contributing :)

All the best :)

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # <issue_number_here>

<hr>

## Please make sure to follow these points ✅

- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] My Pull Request title is in format <code>< issue name ></code> eg <code>design app icon</code>
- [ ] I will upload screenshot/Gif of what I have contributed.
- [ ] I'm JWOC'22 contributor
  
<hr>

## Screenshots / Gif 📸

<hr>

### Thank you!
Your part is over after your pull request is made. Your Pull Request will be merged soon if approved by maintainers. Happy contributing.

### CODE REVIEW

**Comment by Kajal13081** [comment]
@Shreyan-12345 logo is looking quite simple. Try to do something cool

**Comment by Shreyan-12345** [comment]
(final) done

**Comment by Shreyan-12345** [comment]
(final) done

**Comment by Shreyan-12345** [comment]
green color done

**Review by Kajal13081 — APPROVED** [review]

**Comment by Kajal13081** [comment]
Awesome. Merged your PR. Keep it up.

**Pull request merged**
