### PR TITLE
fixed bug not showing songs list

### PR DESCRIPTION
**Pull request by Pdahiya5033**
## JWOC Project 📝

Thanks for your participation in this project for JWOC. 
The contribution will help you get a nice understanding of Android Development. 

Stay determined, stay motivated and Happy Contributing :)

All the best :)

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # <issue_number_here>

<hr>

## Please make sure to follow these points ✅

- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] My Pull Request title is in format <code>< issue name ></code> eg <code>design app icon</code>
- [ ] I will upload screenshot/Gif of what I have contributed.
- [ ] I'm JWOC'22 contributor
  
<hr>

## Screenshots / Gif 📸

<hr>

### Thank you!
Your part is over after your pull request is made. Your Pull Request will be merged soon if approved by maintainers. Happy contributing.

### CODE REVIEW

**Comment by Kajal13081** [comment]
@Pdahiya5033 Have you made the the changes in your own branch?

**Comment by Kajal13081** [comment]
As previously main branch was method2. I renamed the branch. Did you update the project?

**Comment by Pdahiya5033** [comment]
Method 2 was the branch I updated 🥲

**Comment by Kajal13081** [comment]
> Method 2 was the branch I updated 🥲

Okay so it's your own branch right?

**Comment by Pdahiya5033** [comment]
Yes

**Comment by Pdahiya5033** [comment]
Or I should make another branch

**Comment by Kajal13081** [comment]
> Or I should make another branch

If it's your own branch then no need. All the changes need to be made in contributor branch not in main branch. 
Have you updated the project na? Because initially main branch was method2. Then I renamed it.
If you haven't update then do update and make contribution in other branch.

**Comment by Pdahiya5033** [comment]
Ok

**Comment by Pdahiya5033** [comment]
Making another branch

**Comment by Kajal13081** [comment]
Cool open a new PR.

**Pull request closed without merging**
